[package]
name = "png_to_webp"
version = "0.0.3"
edition = "2021"
authors = ["qwadebot"]
description = "A CLI tool to PNG images to WebP format"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
image = "0.25.5"
webp = "0.3.0"
